### ISSUE TITLE
Is this processor really required?

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/processor-flatten-folders#2]
Kdyby všechny procesory (a output mapping + storage) uměly pracovat se souborama/slicovanejma tabulkama o neomezeným zanoření, nemuselo by se placatění vůbec dělat. 

Jedinej use case, co mě napadá, je archiv, ze kterýho chci dostat víc tabulek (tj. musí být v rootu).

**Comment by odinuv** [comment]
Tohle už je asi dneska nereálný změnit
